app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

users:
    resource: "@UsersBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
